### PR TITLE
Move remotedb under db

### PR DESCRIPTION
**Pull request by ebuchman**
I also reran protoc with updated deps - that created a bunch of gross XXX code - hmm

### CODE REVIEW

**Comment by ebuchman** [comment]
@cwgoes

**Comment by cwgoes** [comment]
I get a different result for the compiled protobuf file:

https://gist.github.com/cwgoes/1ea6db7372a4a9c2b27dfb14d9b57f61

I wonder if we're using different `protoc` versions?

```bash
protoc --version

libprotoc 3.4.0
```

**Comment by ebuchman** [comment]
```
ethanbuchman:cosmos-sdk$ protoc --version
libprotoc 3.4.0

```

**Comment by ebuchman** [comment]
Could be different versions of protoc-gen-go ... it doesnt have a version flag/command tho

**Comment by ebuchman** [comment]
I think I'll revert the updated proto for now ? 

What do you think of moving it all under db/remotedb ?

**Comment by cwgoes** [comment]
Both proto files seem to work (at least, they pass the testsuite) - the previous generated file is like `types.pb.go` though, so might be worth staying uniform there.

I think `db/remotedb` makes sense, I just left the file structure from the original PR but I don't see any reason remotedb needs separate folders.

**Pull request merged**
