### PR TITLE
WIP - CLI refactor to work with REST

### LINKED ISSUE #157: Make CLI work better for REST initialization
All the CLI stuff is good for setting up a CLI - REST functionality is almost identical however we don't want to use cobra, only viper config.

### PR DESCRIPTION
**Pull request by rigelrozanski**
closes #157

### CODE REVIEW

**Comment by ebuchman** [comment]
Is anything using this lib besides the SDK? 

If not, let's move it into the SDK. I don't see good reason for it to be here ... it's too magical and has been a source of confusion and bugs before because it's so remote ...

**Comment by rigelrozanski** [comment]
@ebuchman It's a part of tendemint core...

**Comment by melekes** [comment]
> it's too magical and has been a source of confusion and bugs before because it's so remote ...

agree, less magic the better

**Comment by faboweb** [comment]
If I could wish for sth. it would be tests. :-)

Wish

**Comment by ebuchman** [comment]
What exactly is this doing for us ?

**Comment by rigelrozanski** [comment]
I don't even remember, it was something I made when working with Fabo on REST stuff - I think this no longer being used... @faboweb speak now or forever hold yer peace - I'll close if I don't hear back soon

**Pull request closed without merging**
