### PR TITLE
copy log level parsing from tendemint

### PR DESCRIPTION
**Pull request by melekes**
API change due to me not wanting `flags` package to depend on
tendermint's config package.

Refs https://github.com/tendermint/tendermint/issues/504

### CODE REVIEW

**Comment by ethanfrey** [comment]
Looks good to me.  I would enhance the tests though. It doesn't show how default and other packages work, as everything writes to mempool in all cases.

**Comment by ethanfrey** [comment]
Btw, why did you put them in a subdir of cli? There isn't much in cli.  Is it the import of go-wire/data that bothers you?

Huh, on second thought, maybe that is not good....

**Comment by ethanfrey** [comment]
Okay, take a look at the test changes I made. They make it clearer how the different modules play together.  But maybe there is something untested now?

**Comment by melekes** [comment]
> Btw, why did you put them in a subdir of cli? There isn't much in cli. Is it the import of go-wire/data that bothers you?

`flags.ParseLogLevel` just looks cleaner. Should we move these files into cli?

**Comment by melekes** [comment]
> Okay, take a look at the test changes I made. They make it clearer how the different modules play together. But maybe there is something untested now?

Like them! I think we are lacking a test case when there is no "module" key. I will add it.

**Comment by ethanfrey** [comment]
> flags.ParseLogLevel just looks cleaner. Should we move these files into cli?

Or maybe I should move the other flags parsing from cli into cli/flags. It does look nice. I would just get @ebuchman  opinion as flags is a standard name often taken by other packages. In any case, we should be consistent.

**Pull request merged**
