### PR TITLE
[flowrate] refactor clock functions (Refs #16)

### PR DESCRIPTION
**Pull request by melekes**
this commit does not fix the original bug

### CODE REVIEW

**Comment by ethanfrey** [comment]
This is still a WIP?  Or did you fix the bug?

I had this issue too.... rather annoying the randomly failing tests... Somewhere there is an unexpected clock tick... guess sleep is not precise to the millisecond.

**Comment by melekes** [comment]
@ethanfrey https://github.com/tendermint/tmlibs/issues/16#issuecomment-303396143

**Comment by ethanfrey** [comment]
Fair enough.  I took a look at the code myself and left scratching my head.  But random fails is no good... maybe we just disable those tests?? Use some "approx equal" method?

**Comment by melekes** [comment]
I wonder when did it break? maybe something had changed in Go

> Use some "approx equal" method?

I guess we can compare that the time is within range and rates are greater than X

**Comment by adrianbrink** [comment]
@melekes Is there anything blocking this PR from being merged?

**Pull request merged**
